export const MOCK_HOTELS = [
  {
    id: "h1",
    name: "The Golden Leaf Café",
    logo: "/cafe-logo.png",
    description: "A cozy spot for artisanal coffee and gourmet pastries.",
    address: "123 Serene Avenue, Garden District",
    phone: "+1 (555) 123-4567",
    slug: "golden-leaf",
    socials: {
      instagram: "goldenleafcafe",
      facebook: "goldenleafcafe",
    },
  },
  {
    id: "h2",
    name: "Harborview Hotel",
    logo: "/placeholder-logo.png",
    description: "Waterfront dining with panoramic harbor views and seasonal seafood.",
    address: "9 Oceanfront Blvd, Harbor City",
    phone: "+1 (555) 234-7890",
    slug: "harborview",
    socials: {
      instagram: "harborviewhotel",
      facebook: "harborviewhotel",
    },
  },
  {
    id: "h3",
    name: "Summit Rooftop",
    logo: "/placeholder-logo.svg",
    description: "Sky-high cocktails and tapas with a skyline backdrop.",
    address: "77 Peak Street, Downtown",
    phone: "+1 (555) 987-6543",
    slug: "summit-rooftop",
    socials: {
      instagram: "summitrooftop",
      facebook: "summitrooftop",
    },
  },
]

export const MOCK_HOTEL = MOCK_HOTELS[0]

export const MOCK_MENUS = [
  {
    id: "menu-1",
    name: "Golden Leaf Café",
    slug: "golden-leaf",
    location: "Garden District",
    status: "Live",
    scans30d: 1248,
  },
  {
    id: "menu-2",
    name: "Harborview Hotel",
    slug: "harborview",
    location: "Waterfront",
    status: "Live",
    scans30d: 932,
  },
  {
    id: "menu-3",
    name: "Summit Rooftop",
    slug: "summit-rooftop",
    location: "Downtown",
    status: "Draft",
    scans30d: 187,
  },
]

export const MOCK_CATEGORIES = [
  { id: "c1", name: "Hot Coffee", itemCount: 8 },
  { id: "c2", name: "Iced Drinks", itemCount: 5 },
  { id: "c3", name: "Gourmet Pastries", itemCount: 6 },
  { id: "c4", name: "Breakfast Plates", itemCount: 4 },
  { id: "c5", name: "Fresh Juices", itemCount: 3 },
]

export const MOCK_MENU_ITEMS = [
  {
    id: "m1",
    menuId: "menu-1",
    categoryId: "c1",
    name: "Classic Espresso",
    description: "Rich and bold single shot of our signature house blend.",
    price: 3.5,
    image: "/espresso-shot.png",
    available: true,
  },
  {
    id: "m2",
    menuId: "menu-1",
    categoryId: "c1",
    name: "Caramel Macchiato",
    description:
      "Freshly steamed milk with vanilla-flavored syrup marked with espresso and topped with caramel drizzle.",
    price: 5.25,
    image: "/macchiato.jpg",
    available: true,
  },
  {
    id: "m3",
    menuId: "menu-1",
    categoryId: "c3",
    name: "Butter Croissant",
    description: "Flaky, golden-brown pastry made with real French butter.",
    price: 3.75,
    image: "/golden-croissant.png",
    available: true,
  },
  {
    id: "m4",
    menuId: "menu-1",
    categoryId: "c2",
    name: "Passion Fruit Iced Tea",
    description: "Refreshing black tea infused with tropical passion fruit flavors.",
    price: 4.5,
    image: "/iced-tea.png",
    available: false,
  },
  {
    id: "m5",
    menuId: "menu-2",
    categoryId: "c4",
    name: "Seaside Brunch Platter",
    description: "Smoked salmon, poached eggs, and lemon-dill hollandaise with greens.",
    price: 16.5,
    image: "/placeholder.jpg",
    available: true,
  },
  {
    id: "m6",
    menuId: "menu-2",
    categoryId: "c5",
    name: "Citrus Sunrise Juice",
    description: "Fresh orange, grapefruit, and mint over crushed ice.",
    price: 6.0,
    image: "/glass-of-orange-juice.png",
    available: true,
  },
  {
    id: "m7",
    menuId: "menu-3",
    categoryId: "c2",
    name: "Cold Brew Tonic",
    description: "Bright espresso cold brew over tonic with a grapefruit twist.",
    price: 5.75,
    image: "/placeholder.svg",
    available: true,
  },
  {
    id: "m8",
    menuId: "menu-3",
    categoryId: "c3",
    name: "Midnight Lava Cake",
    description: "Decadent dark chocolate cake with molten center and vanilla bean gelato.",
    price: 8.25,
    image: "/decadent-lava-cake.png",
    available: true,
  },
]
